#ifndef FILEPARSER_H
#define FILEPARSER_H

#include <QByteArray>
#include <QString>
#include <QDateTime>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlError>
//#include "rapidjson/document.h"
//#include "rapidjson/writer.h"
#include "rapidjson/prettywriter.h"
#include "rapidjson/stringbuffer.h"

class FileParser
{
public:
    FileParser();
    ~FileParser();

public:
    void YiPiaoTongTradeFile(rapidjson::PrettyWriter<rapidjson::StringBuffer>& writer
                             , const QByteArray& ba);
    void YiKaTongTradeFile(rapidjson::PrettyWriter<rapidjson::StringBuffer>& writer
                           , const QByteArray& ba);
    void PhoneTicketTradeFile(rapidjson::PrettyWriter<rapidjson::StringBuffer>& writer
                              , const QByteArray& ba);
    void BankCardTradeFile(rapidjson::PrettyWriter<rapidjson::StringBuffer>& writer
                           , const QByteArray& ba);
    void QRCodeTradeFile(rapidjson::PrettyWriter<rapidjson::StringBuffer>& writer
                         , const QByteArray& ba);

    void OpenDB(const QString& host, const QString& database, int port, const QString& usr, const QString& pwd);

private:
    void CloseDB();

    QSqlDatabase db;

    const QString txn_sjt_sale = "INSERT INTO txn_sjt_sale%1 (bom_shift_id, card_init_date, change_value, device_id, InitBatchCode, language_flag, line_id, mode_code, operator_id, original_value, paymentmeans, station_id, sub_global_message_id, tac, tac_sam_id, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_price_value, ticket_remaining_value, ticket_sn, ticket_status, ticket_type, ticket_phy_id, transaction_date_time_hi, transaction_date_time_lo, transaction_status, transaction_type, transaction_value, txn_type, udsn, valid_end_date, valid_start_date) VALUES (:bom_shift_id, :card_init_date, :change_value, :device_id, :InitBatchCode, :language_flag, :line_id, :mode_code, :operator_id, :original_value, :paymentmeans, :station_id, :sub_global_message_id, :tac, :tac_sam_id, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_price_value, :ticket_remaining_value, :ticket_sn, :ticket_status, :ticket_type, :ticket_phy_id, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_status, :transaction_type, :transaction_value, :txn_type, :udsn, :valid_end_date, :valid_start_date)";

    const QString txn_ypt_entry = "INSERT INTO txn_ypt_entry%1 (device_id, line_id, mode_code, remaining_value, station_id, sub_global_message_id, tac, tac_sam_id, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_remaining_value, ticket_sn, ticket_status, ticket_type, ticket_phy_id, trans_status_after_trans, trans_status_before_trans, transaction_date_time_hi, transaction_date_time_lo, transaction_type, txn_type, udsn) VALUES (:device_id, :line_id, :mode_code, :remaining_value, :station_id, :sub_global_message_id, :tac, :tac_sam_id, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_remaining_value, :ticket_sn, :ticket_status, :ticket_type, :ticket_phy_id, :trans_status_after_trans, :trans_status_before_trans, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :txn_type, :udsn)";

    const QString txn_ypt_exit = "INSERT INTO txn_ypt_exit%1 (accumulation_bonus, current_bonus, deduce_location, device_id, entry_device_id, entry_time_hi, entry_time_lo, join_concession_id, join_concession_percentage, join_concession_type, join_concession_value, line_id, mode_code, original_value, pile_concession_id, sam_sn, sjt_recycle_flag, station_id, sub_global_message_id, tac, tac_sam_id, terminate_number, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_remaining_value, ticket_sn, ticket_status, ticket_type, ticket_phy_id, trans_status_after_trans, trans_status_before_trans, transaction_date_time_hi, transaction_date_time_lo, transaction_type, transaction_value, txn_type, udsn) VALUES (:accumulation_bonus, :current_bonus, :deduce_location, :device_id, :entry_device_id, :entry_time_hi, :entry_time_lo, :join_concession_id, :join_concession_percentage, :join_concession_type, :join_concession_value, :line_id, :mode_code, :original_value, :pile_concession_id, :sam_sn, :sjt_recycle_flag, :station_id, :sub_global_message_id, :tac, :tac_sam_id, :terminate_number, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_remaining_value, :ticket_sn, :ticket_status, :ticket_type, :ticket_phy_id, :trans_status_after_trans, :trans_status_before_trans, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :transaction_value, :txn_type, :udsn)";

    const QString txn_ypt_update = "INSERT INTO txn_ypt_update%1 (bom_shift, device_id, line_id, mode_code, operator_id, paymentmeans, sale_device_id, station_id, sub_global_message_id, surcharge_area, surcharge_code, tac, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_phy_id, ticket_remaining_value, ticket_sale_value, ticket_sn, ticket_status, ticket_type, trans_status_after_trans, trans_status_befor_trans, transaction_date_time_hi, transaction_date_time_lo, transaction_type, transaction_value, txn_type, udsn) VALUES (:bom_shift, :device_id, :line_id, :mode_code, :operator_id, :paymentmeans, :sale_device_id, :station_id, :sub_global_message_id, :surcharge_area, :surcharge_code, :tac, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_phy_id, :ticket_remaining_value, :ticket_sale_value, :ticket_sn, :ticket_status, :ticket_type, :trans_status_after_trans, :trans_status_befor_trans, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :transaction_value, :txn_type, :udsn)";

    const QString txn_bank_entry = "INSERT INTO txn_bank_entry%1 (auth_code, bank_code, device_id, line_id, mode_code, pos_no, pre_auth_value, primary_account, reserve_one, reserve_two, station_id, sub_global_message_id, tac, tac_sam_id, termin_no, ticket_catalog_id, ticket_family_type, ticket_type, transaction_date_time_hi, transaction_date_time_lo, transaction_type, txn_type, udsn) VALUES (:auth_code, :bank_code, :device_id, :line_id, :mode_code, :pos_no, :pre_auth_value, :primary_account, :reserve_one, :reserve_two, :station_id, :sub_global_message_id, :tac, :tac_sam_id, :termin_no, :ticket_catalog_id, :ticket_family_type, :ticket_type, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :txn_type, :udsn)";

    const QString txn_bank_exit = "INSERT INTO txn_bank_exit%1 (bank_code, device_id, dis_trans_value, line_id, mode_code, pos_no, primary_account, reserve_one, reserve_two, start_device, start_time_hi, start_time_lo, station_id, sub_global_message_id, tac, tac_sam_id, termin_no, ticket_catalog_id, ticket_family_type, ticket_type, trans_value, transaction_date_time_hi, transaction_date_time_lo, transaction_type, txn_type, udsn) VALUES (:bank_code, :device_id, :dis_trans_value, :line_id, :mode_code, :pos_no, :primary_account, :reserve_one, :reserve_two, :start_device, :start_time_hi, :start_time_lo, :station_id, :sub_global_message_id, :tac, :tac_sam_id, :termin_no, :ticket_catalog_id, :ticket_family_type, :ticket_type, :trans_value, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :txn_type, :udsn)";

    const QString txn_qr_code_entry = "INSERT INTO txn_qr_code_entry%1 (device_id, line_id, mode_code, qr_code_id, reserve_one, reserve_two, station_id, sub_global_message_id, tac, tac_sam_id, ticket_catalog_id, ticket_family_type, ticket_type, transaction_date_time_hi, transaction_date_time_lo, transaction_type, txn_type, udsn, uid) VALUES (:device_id, :line_id, :mode_code, :qr_code_id, :reserve_one, :reserve_two, :station_id, :sub_global_message_id, :tac, :tac_sam_id, :ticket_catalog_id, :ticket_family_type, :ticket_type, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :txn_type, :udsn, :uid)";

    const QString txn_qr_code_exit = "INSERT INTO txn_qr_code_exit%1 (device_id, line_id, mode_code, qr_code_id, reserve_one, reserve_two, start_device, start_time_hi, start_time_lo, station_id, sub_global_message_id, tac, tac_sam_id, ticket_catalog_id, ticket_family_type, ticket_type, trans_value, transaction_date_time_hi, transaction_date_time_lo, transaction_type, txn_type, udsn, uid) VALUES (:device_id, :line_id, :mode_code, :qr_code_id, :reserve_one, :reserve_two, :start_device, :start_time_hi, :start_time_lo, :station_id, :sub_global_message_id, :tac, :tac_sam_id, :ticket_catalog_id, :ticket_family_type, :ticket_type, :trans_value, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :txn_type, :udsn, :uid)";

    const QString txn_qr_code_update = "INSERT INTO txn_qr_code_update%1 (bom_shift_id, device_id, line_id, mode_code, operator_id, paymentmeans, qr_code_id, reserve_one, reserve_two, sale_device_id, station_id, sub_global_message_id, surcharge_area, surcharge_code, tac, tac_sam_id, ticket_catalog_id, ticket_family_type, ticket_sale_value, ticket_type, trans_status_after_trans, trans_status_before_trans, transaction_date_time_hi, transaction_date_time_lo, transaction_type, transaction_value, txn_type, udsn, uid) VALUES (:bom_shift_id, :device_id, :line_id, :mode_code, :operator_id, :paymentmeans, :qr_code_id, :reserve_one, :reserve_two, :sale_device_id, :station_id, :sub_global_message_id, :surcharge_area, :surcharge_code, :tac, :tac_sam_id, :ticket_catalog_id, :ticket_family_type, :ticket_sale_value, :ticket_type, :trans_status_after_trans, :trans_status_before_trans, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :transaction_value, :txn_type, :udsn, :uid)";

    const QString txn_sjt_refund = "INSERT INTO txn_sjt_refund%1 (bom_shift_id, card_init_date, device_id, InitBatchCode, line_id, mode_code, operator_id, price_value, refund_reason, station_id, sub_global_message_id, tac, tac_sam_id, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_remaining_value, ticket_sn, ticket_status, ticket_type, ticket_phy_id, transaction_date_time_hi, transaction_date_time_lo, transaction_status, transaction_type, txn_type, udsn) VALUES (:bom_shift_id, :card_init_date, :device_id, :InitBatchCode, :line_id, :mode_code, :operator_id, :price_value, :refund_reason, :station_id, :sub_global_message_id, :tac, :tac_sam_id, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_remaining_value, :ticket_sn, :ticket_status, :ticket_type, :ticket_phy_id, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_status, :transaction_type, :txn_type, :udsn)";

    const QString txn_svc_charge = "INSERT INTO txn_svc_charge%1 (app_sn, bank_card_code, bank_code, bank_trans_sn, biz_code, bom_shift_id, card_issue_date, charge_terminate_number, device_id, e_purse_transaction_type, host_transaction_time_hi, host_transaction_time_lo, issuer_code, last_add_transaction_value, last_add_value_device_id, last_add_value_sam_id, last_add_value_time_hi, last_add_value_time_lo, last_add_value_udsn, line_id, mode_code, new_remaining_value, operator_id, payment_means, pos_no, real_transaction_value, station_id, sub_global_message_id, tac, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_phy_id, ticket_remaining_value, ticket_sn, ticket_status, ticket_type, transaction_date_time_hi, transaction_date_time_lo, transaction_type, transcation_value, txn_type, udsn, valid_date_after_add_value, valid_date_before_add_value) VALUES (:app_sn, :bank_card_code, :bank_code, :bank_trans_sn, :biz_code, :bom_shift_id, :card_issue_date, :charge_terminate_number, :device_id, :e_purse_transaction_type, :host_transaction_time_hi, :host_transaction_time_lo, :issuer_code, :last_add_transaction_value, :last_add_value_device_id, :last_add_value_sam_id, :last_add_value_time_hi, :last_add_value_time_lo, :last_add_value_udsn, :line_id, :mode_code, :new_remaining_value, :operator_id, :payment_means, :pos_no, :real_transaction_value, :station_id, :sub_global_message_id, :tac, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_phy_id, :ticket_remaining_value, :ticket_sn, :ticket_status, :ticket_type, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :transcation_value, :txn_type, :udsn, :valid_date_after_add_value, :valid_date_before_add_value)";

    const QString txn_ykt_block = "INSERT INTO txn_ykt_block%1 (add_value_date, block_reason_code, bom_shift_id, card_ver, city_code_belong_location, city_code_trans_location, device_id, e_purse_transaction_type, line_id, main_card_type, mode_code, operator_id, recharge_sn, sak, sale_date, sam_sn, station_id, sub_card_type, sub_global_message_id, system_trace_sn, tac, tac_sam_id, terminate_number, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_phy_id, ticket_remaining_value, ticket_sn, ticket_status, ticket_type, transaction_date_time_hi, transaction_date_time_lo, transaction_type, txn_type, udsn) VALUES (:add_value_date, :block_reason_code, :bom_shift_id, :card_ver, :city_code_belong_location, :city_code_trans_location, :device_id, :e_purse_transaction_type, :line_id, :main_card_type, :mode_code, :operator_id, :recharge_sn, :sak, :sale_date, :sam_sn, :station_id, :sub_card_type, :sub_global_message_id, :system_trace_sn, :tac, :tac_sam_id, :terminate_number, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_phy_id, :ticket_remaining_value, :ticket_sn, :ticket_status, :ticket_type, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :txn_type, :udsn)";

    const QString txn_ykt_charge = "INSERT INTO txn_ykt_charge%1 (add_value_date, app_sn, bank_card_code, bank_code, bank_trans_sn, biz_code, bom_shift_id, card_issue_date, card_ver, charge_terminate_number, city_code_belong_location, city_code_trans_location, device_id, e_purse_transaction_type, host_transaction_time_hi, host_transaction_time_lo, issuer_code, last_add_transaction_value, last_add_value_device_id, last_add_value_sam_id, last_add_value_time_hi, last_add_value_time_lo, last_add_value_udsn, line_id, main_card_type, mode_code, new_remaining_value, operator_id, payment_means, pos_no, real_transaction_value, recharge_sn, sak, sale_date, sam_sn, station_id, sub_card_type, sub_global_message_id, system_trace_sn, tac, tac_sam_id, terminate_number, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_phy_id, ticket_remaining_value, ticket_sn, ticket_status, ticket_type, transaction_date_time_hi, transaction_date_time_lo, transaction_type, transcation_value, txn_type, udsn, valid_date_after_add_value, valid_date_before_add_value) VALUES (:add_value_date, :app_sn, :bank_card_code, :bank_code, :bank_trans_sn, :biz_code, :bom_shift_id, :card_issue_date, :card_ver, :charge_terminate_number, :city_code_belong_location, :city_code_trans_location, :device_id, :e_purse_transaction_type, :host_transaction_time_hi, :host_transaction_time_lo, :issuer_code, :last_add_transaction_value, :last_add_value_device_id, :last_add_value_sam_id, :last_add_value_time_hi, :last_add_value_time_lo, :last_add_value_udsn, :line_id, :main_card_type, :mode_code, :new_remaining_value, :operator_id, :payment_means, :pos_no, :real_transaction_value, :recharge_sn, :sak, :sale_date, :sam_sn, :station_id, :sub_card_type, :sub_global_message_id, :system_trace_sn, :tac, :tac_sam_id, :terminate_number, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_phy_id, :ticket_remaining_value, :ticket_sn, :ticket_status, :ticket_type, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :transcation_value, :txn_type, :udsn, :valid_date_after_add_value, :valid_date_before_add_value)";

    const QString txn_ykt_exit = "INSERT INTO txn_ykt_exit%1 (accumulation_bonus, add_value_date, card_ver, city_code_belong_location, city_code_trans_location, current_bonus, device_id, e_purse_transaction_type, entry_device_id, entry_time_hi, entry_time_lo, join_concession_id, join_concession_percentage, join_concession_type, join_concession_value, line_id, main_card_type, mode_code, original_value, pile_concession_id, recharge_sn, remaining_value_after_trans, remaining_value_befor_trans, sak, sale_date, sam_sn, station_id, sub_card_type, sub_global_message_id, system_trace_sn, tac, tac_sam_id, terminate_number, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_phy_id, ticket_remaining_value, ticket_sn, ticket_status, ticket_type, trans_status_after_trans, trans_status_before_trans, transaction_date_time_hi, transaction_date_time_lo, transaction_type, transaction_value, txn_type, udsn) VALUES (:accumulation_bonus, :add_value_date, :card_ver, :city_code_belong_location, :city_code_trans_location, :current_bonus, :device_id, :e_purse_transaction_type, :entry_device_id, :entry_time_hi, :entry_time_lo, :join_concession_id, :join_concession_percentage, :join_concession_type, :join_concession_value, :line_id, :main_card_type, :mode_code, :original_value, :pile_concession_id, :recharge_sn, :remaining_value_after_trans, :remaining_value_befor_trans, :sak, :sale_date, :sam_sn, :station_id, :sub_card_type, :sub_global_message_id, :system_trace_sn, :tac, :tac_sam_id, :terminate_number, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_phy_id, :ticket_remaining_value, :ticket_sn, :ticket_status, :ticket_type, :trans_status_after_trans, :trans_status_before_trans, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :transaction_value, :txn_type, :udsn)";

    const QString txn_ykt_entry = "INSERT INTO txn_ykt_entry%1 (add_value_date, card_ver, city_code_belong_location, city_code_trans_location, device_id, e_purse_transaction_type, line_id, main_card_type, mode_code, recharge_sn, remaining_value, sak, sale_date, sam_sn, station_id, sub_card_type, sub_global_message_id, system_trace_sn, tac, tac_sam_id, terminate_number, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_remaining_value, ticket_sn, ticket_status, ticket_type, ticket_phy_id, trans_status_after_trans, trans_status_before_trans, transaction_date_time_hi, transaction_date_time_lo, transaction_type, txn_type, udsn) VALUES (:add_value_date, :card_ver, :city_code_belong_location, :city_code_trans_location, :device_id, :e_purse_transaction_type, :line_id, :main_card_type, :mode_code, :recharge_sn, :remaining_value, :sak, :sale_date, :sam_sn, :station_id, :sub_card_type, :sub_global_message_id, :system_trace_sn, :tac, :tac_sam_id, :terminate_number, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_remaining_value, :ticket_sn, :ticket_status, :ticket_type, :ticket_phy_id, :trans_status_after_trans, :trans_status_before_trans, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :txn_type, :udsn)";

    const QString txn_ykt_update = "INSERT INTO txn_ykt_update%1 (add_value_date, bom_shift, card_ver, city_code_belong_location, city_code_trans_location, device_id, e_purse_transaction_type, line_id, main_card_type, mode_code, operator_id, paymentmeans, recharge_sn, sak, sale_date, sale_device_id, sam_sn, station_id, sub_card_type, sub_global_message_id, surcharge_area, surcharge_code, system_trace_sn, tac, tac_sam_id, terminate_number, test_flag, ticket_catalog_id, ticket_family_type, ticket_logic_id, ticket_phy_id, ticket_remaining_value, ticket_sale_value, ticket_sn, ticket_status, ticket_type, trans_status_after_trans, trans_status_befor_trans, transaction_date_time_hi, transaction_date_time_lo, transaction_type, transaction_value, txn_type, udsn) VALUES (:add_value_date, :bom_shift, :card_ver, :city_code_belong_location, :city_code_trans_location, :device_id, :e_purse_transaction_type, :line_id, :main_card_type, :mode_code, :operator_id, :paymentmeans, :recharge_sn, :sak, :sale_date, :sale_device_id, :sam_sn, :station_id, :sub_card_type, :sub_global_message_id, :surcharge_area, :surcharge_code, :system_trace_sn, :tac, :tac_sam_id, :terminate_number, :test_flag, :ticket_catalog_id, :ticket_family_type, :ticket_logic_id, :ticket_phy_id, :ticket_remaining_value, :ticket_sale_value, :ticket_sn, :ticket_status, :ticket_type, :trans_status_after_trans, :trans_status_befor_trans, :transaction_date_time_hi, :transaction_date_time_lo, :transaction_type, :transaction_value, :txn_type, :udsn)";
};

#endif // FILEPARSER_H
